### ISSUE TITLE
PATH bug for Update platforms

### ISSUE THREAD

**Issue by felipevicens** [sonata-nfv/tng-vnv-platform-adapter#124]
The expected behaviour is when we send the fields to update, from portal, that should update that only fields in the database of PA

**Comment by luishensruiz** [comment]
update the code. All fields except SP name (the primary key) can be udpated

**Comment by felipevicens** [comment]
Still not working return 500

KeyError

KeyError: 'host'
Traceback (most recent call last)

**Comment by anapolg** [comment]
The thing is, as it is right now it requires all the platform information to be sent (but the name). A PATCH updates just the information that changes which could be just the host, the username... or any field the user changes. No need to send all the data again to update the platform so the Portal is sending a body like:
{
    "host": "10.10.10.10"
}

and just that information. If you (@felipevicens @luishens01 ) want to update the whole object please change the PATCH by a PUT and I'll change Portal request to send you everything.

**Comment by luishensruiz** [comment]
Fixed and tested from the portal. Pending fo more test from people.

**Comment by anapolg** [comment]
Working fine! Thanks a lot @luishens01 . You can close the issue
